### PR TITLE
Fix factor.h

### PR DESCRIPTION
**Pull request by Tyilo**
`pr` shouldn't be local

### CODE REVIEW

**Comment by simonlindholm** [comment]
You really seem to find all the crufty corners of KACTL... While you're changing factor.h, do you mind:

- using `pr.assign(all(p));` instead of copy(..., back_inserter(pr))
- using `__gcd` instead of `gcd`, and removing the include of `euclid.h`
- adding an include for `ModMulLL.h`
- adding a note to the documentation that it returns the factors of the number *without duplicates*

?

**Comment by Tyilo** [comment]
Do we want to include `ModMulLL.h` when `MillerRabin.h` includes `ModMullLL.h`?

Shouldn't there be a relation between `const init bits` in `ModMulLL.h` and `void init(int bits)` in `factor.h`?
Maybe replace `init` with:

```
void init() {
  vi p = eratosthenes_sieve(1 << ((64 - bits + 2) / 3));
  pr.assign(all(p));
}
```

**Comment by simonlindholm** [comment]
> Do we want to include ModMulLL.h when MillerRabin.h includes ModMullLL.h?

Ah, I missed that. I guess it still doesn't hurt?

> Shouldn't there be a relation between const init bits in ModMulLL.h and void init(int bits) in factor.h?

Mmm, perhaps. No real opinion, honestly -- I can see arguments both ways, and I haven't actually ever used this algorithm in a contest, so I don't care that much about it.

**Comment by Tyilo** [comment]
Done :)

**Comment by simonlindholm** [comment]
Thanks!

**Pull request merged**
