### PR TITLE
Only hash supported languages (c++)

### PR DESCRIPTION
**Pull request by Tyilo**

### CODE REVIEW

**Comment by simonlindholm** [comment]
Can you include Java as well? `cpp` works there too. (For Python you start hitting problems with `//` -- it would be possible to skip hashing only when that happens, or more generally when the hash script fails, but maybe that's just confusing.)

**Comment by simonlindholm** [comment]
Yes. The C preprocessor is harmless to run on most files, but Java especially so since it uses the same syntax for comments as C++.

**Comment by simonlindholm** [comment]
Thanks! Fix the conflict and I'll merge.

**Comment by Tyilo** [comment]
Fixed

**Pull request merged**
